const tasks=[
{id:'1.1',number:1,prototype:1,section:'Практические задачи',topic:'Маршруты',text:'Пользуясь описанием, определите, какими цифрами на плане обозначены населённые пункты.',demo:false,new:false},
{id:'2.1',number:2,prototype:1,section:'Практические задачи',topic:'Маршруты',text:'Найдите расстояние по заданному маршруту.',demo:false,new:false},
{id:'3.1',number:3,prototype:1,section:'Практические задачи',topic:'Маршруты',text:'Найдите расстояние между населёнными пунктами по прямой.',demo:false,new:false},
{id:'4.1',number:4,prototype:1,section:'Практические задачи',topic:'Маршруты',text:'Определите время движения по заданному маршруту.',demo:false,new:false},
{id:'5.1',number:5,prototype:1,section:'Практические задачи',topic:'Маршруты',text:'Сравните стоимость набора товаров и выберите наиболее выгодный вариант.',demo:false,new:false},
{id:'6.1',number:6,prototype:1,section:'Алгебра',topic:'Дроби',text:'Вычислите значение числового выражения с обыкновенными дробями.',demo:false,new:false},
{id:'7.1',number:7,prototype:1,section:'Алгебра',topic:'Координатная прямая',text:'Определите положение числа на координатной прямой.',demo:false,new:false},
{id:'8.1',number:8,prototype:1,section:'Алгебра',topic:'Степени и корни',text:'Найдите значение выражения, используя свойства степеней и корней.',demo:false,new:true},
{id:'8.2',number:8,prototype:2,section:'Алгебра',topic:'Степени и корни',text:'Упростите выражение со степенями и вычислите его значение.',demo:false,new:false},
{id:'9.1',number:9,prototype:1,section:'Алгебра',topic:'Уравнения',text:'Решите уравнение и запишите полученный корень.',demo:false,new:false},
{id:'10.1',number:10,prototype:1,section:'Алгебра',topic:'Вероятности',text:'Найдите вероятность случайного события.',demo:false,new:false},
{id:'10.2',number:10,prototype:2,section:'Алгебра',topic:'Вероятности',text:'По условию случайного эксперимента вычислите вероятность события.',demo:true,new:false},
{id:'11.1',number:11,prototype:1,section:'Алгебра',topic:'Графики функций',text:'Установите соответствие между графиками функций и формулами.',demo:false,new:false},
{id:'12.1',number:12,prototype:1,section:'Алгебра',topic:'Расчёты по формулам',text:'Выполните расчёт по заданной формуле.',demo:false,new:false},
{id:'13.1',number:13,prototype:1,section:'Алгебра',topic:'Неравенства',text:'Решите неравенство и выберите соответствующий промежуток.',demo:false,new:false},
{id:'14.1',number:14,prototype:1,section:'Алгебра',topic:'Прогрессии',text:'Решите задачу на арифметическую или геометрическую прогрессию.',demo:false,new:false},
{id:'15.1',number:15,prototype:1,section:'Геометрия',topic:'Треугольники и их элементы',text:'Решите задачу о треугольнике и его элементах.',demo:false,new:false},
{id:'16.1',number:16,prototype:1,section:'Геометрия',topic:'Окружность, круг и их элементы',text:'Решите задачу, связанную с окружностью или кругом.',demo:false,new:false},
{id:'17.1',number:17,prototype:1,section:'Геометрия',topic:'Четырёхугольники',text:'Используйте свойства четырёхугольника для вычисления неизвестной величины.',demo:false,new:false},
{id:'18.1',number:18,prototype:1,section:'Геометрия',topic:'Клетчатая бумага',text:'Найдите геометрическую величину по рисунку на клетчатой бумаге.',demo:false,new:false},
{id:'19.1',number:19,prototype:1,section:'Геометрия',topic:'Анализ геометрических высказываний',text:'Определите номера верных геометрических утверждений.',demo:false,new:false},
{id:'20.1',number:20,prototype:1,section:'Развёрнутый ответ',topic:'Выражения, уравнения и неравенства',text:'Выполните преобразования и запишите развёрнутое решение.',demo:false,new:false},
{id:'21.1',number:21,prototype:1,section:'Развёрнутый ответ',topic:'Текстовые задачи',text:'Решите текстовую задачу с полным обоснованием.',demo:false,new:false},
{id:'22.1',number:22,prototype:1,section:'Развёрнутый ответ',topic:'Построение графиков функций',text:'Постройте график функции и ответьте на дополнительный вопрос.',demo:false,new:false},
{id:'23.1',number:23,prototype:1,section:'Развёрнутый ответ',topic:'Геометрические задачи на вычисление',text:'Решите геометрическую задачу на вычисление.',demo:false,new:false},
{id:'24.1',number:24,prototype:1,section:'Развёрнутый ответ',topic:'Геометрические задачи на доказательство',text:'Докажите требуемое геометрическое утверждение.',demo:false,new:false},
{id:'25.1',number:25,prototype:1,section:'Развёрнутый ответ',topic:'Геометрические задачи повышенной сложности',text:'Решите геометрическую задачу повышенной сложности.',demo:false,new:false}
];
let variant=JSON.parse(localStorage.getItem('mathoge-current')||'[]');
const titles={home:'Главная',bank:'Банк заданий',builder:'Собрать вариант',generator:'Сгенерировать вариант',saved:'Мои варианты'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function saveCurrent(){localStorage.setItem('mathoge-current',JSON.stringify(variant));updateCounters();renderBuilder();}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function go(page){$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+page).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=titles[page];if(page==='bank')renderTasks();if(page==='builder')renderBuilder();if(page==='saved')renderSaved();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#showVariantBtn').onclick=()=>go('builder');
function updateCounters(){const n=variant.length;$('#variantCount').textContent=n;$('#summaryCount').textContent=n;$('#summaryPart1').textContent=variant.filter(t=>t.number<=19).length;$('#summaryPart2').textContent=variant.filter(t=>t.number>=20).length;$('#currentVariantText').textContent=n?`В текущем варианте ${n} заданий. Можно продолжить сборку или сохранить подборку.`:'Откройте банк заданий или конструктор и добавьте первые задачи.';$('#miniVariant').innerHTML=variant.slice(0,12).map(t=>`<span class="mini-chip">№${t.number} · ${t.id}</span>`).join('')}
function addTask(id){const task=tasks.find(t=>t.id===id);if(!task)return;if(variant.some(t=>t.id===id)){variant=variant.filter(t=>t.id!==id);toast('Задание удалено из варианта')}else{variant.push(task);variant.sort((a,b)=>a.number-b.number);toast('Задание добавлено')}saveCurrent();renderTasks()}
function renderTasks(){const q=$('#searchInput').value.trim().toLowerCase(),num=$('#numberFilter').value,sec=$('#sectionFilter').value,proto=$('#prototypeFilter').value,demo=$('#demoFilter').checked,isNew=$('#newFilter').checked;let list=tasks.filter(t=>(!q||`${t.id} ${t.topic} ${t.text}`.toLowerCase().includes(q))&&(!num||t.number==num)&&(!sec||t.section===sec)&&(!proto||t.prototype==proto)&&(!demo||t.demo)&&(!isNew||t.new));list.sort((a,b)=>$('#sortSelect').value==='id'?a.id.localeCompare(b.id,undefined,{numeric:true}):a.number-b.number);$('#resultCount').textContent=list.length;$('#taskList').innerHTML=list.map(t=>{const added=variant.some(v=>v.id===t.id);return `<article class="task-card"><div><div class="task-meta"><span class="tag number">№${t.number}</span><span class="tag">${t.section}</span><span class="tag">${t.topic}</span><span class="tag">Прототип ${t.prototype}</span>${t.demo?'<span class="tag demo">DEMO</span>':''}${t.new?'<span class="tag new">NEW</span>':''}</div><h4>${t.topic}</h4><p>${t.text}</p></div><div class="task-side"><span class="task-id">ID ${t.id}</span><button class="add-button ${added?'added':''}" data-add="${t.id}">${added?'✓ Добавлено':'+ В вариант'}</button></div></article>`}).join('')||'<div class="panel"><p class="muted">По выбранным фильтрам заданий не найдено.</p></div>';$$('[data-add]').forEach(b=>b.onclick=()=>addTask(b.dataset.add))}
function renderBuilder(){const list=$('#builderList'),empty=$('#builderEmpty');empty.style.display=variant.length?'none':'block';list.innerHTML=variant.map((t,i)=>`<div class="builder-item"><div class="builder-number">${i+1}</div><div><strong>№${t.number}. ${t.topic}</strong><small>${t.id} · ${t.section} · прототип ${t.prototype}</small></div><button class="remove-button" data-remove="${t.id}">×</button></div>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{variant=variant.filter(t=>t.id!==b.dataset.remove);saveCurrent();toast('Задание удалено')});updateCounters()}
function initFilters(){const sel=$('#numberFilter');for(let i=1;i<=25;i++)sel.insertAdjacentHTML('beforeend',`<option value="${i}">№${i}</option>`);['searchInput','numberFilter','sectionFilter','prototypeFilter','demoFilter','newFilter','sortSelect'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',renderTasks));$('#resetFilters').onclick=()=>{$('#searchInput').value='';$('#numberFilter').value='';$('#sectionFilter').value='';$('#prototypeFilter').value='';$('#demoFilter').checked=false;$('#newFilter').checked=false;renderTasks()}}
const topicByNumber={1:'Практический блок',2:'Практический блок',3:'Практический блок',4:'Практический блок',5:'Практический блок',6:'Дроби',7:'Координатная прямая',8:'Степени и корни',9:'Уравнения',10:'Вероятности',11:'Графики функций',12:'Расчёты по формулам',13:'Неравенства',14:'Прогрессии',15:'Треугольники',16:'Окружность',17:'Четырёхугольники',18:'Клетчатая бумага',19:'Высказывания',20:'Алгебра, часть 2',21:'Текстовая задача',22:'Графики, часть 2',23:'Геометрия',24:'Доказательство',25:'Сложная геометрия'};
const genCounts={};function initGenerator(){for(let i=1;i<=25;i++)genCounts[i]=0;$('#generatorRows').innerHTML=Array.from({length:25},(_,k)=>{const n=k+1;return `<div class="generator-row"><strong>№${n}</strong><span>${topicByNumber[n]}</span><div class="stepper"><button data-step="${n}" data-delta="-1">−</button><b id="gc${n}">0</b><button data-step="${n}" data-delta="1">+</button></div></div>`}).join('');$$('[data-step]').forEach(b=>b.onclick=()=>{const n=+b.dataset.step;genCounts[n]=Math.max(0,Math.min(5,genCounts[n]+(+b.dataset.delta)));$('#gc'+n).textContent=genCounts[n];updateGenTotal()});$('#standardPresetBtn').onclick=()=>{for(let i=1;i<=25;i++){genCounts[i]=i<=19?1:0;$('#gc'+i).textContent=genCounts[i]}updateGenTotal()};$('#generateBtn').onclick=generateVariant}
function updateGenTotal(){$('#generationTotal').textContent=Object.values(genCounts).reduce((a,b)=>a+b,0)}
function generateVariant(){const generated=[];for(let n=1;n<=25;n++){const pool=tasks.filter(t=>t.number===n);for(let k=0;k<genCounts[n]&&pool.length;k++){const candidates=pool.filter(t=>!generated.some(g=>g.id===t.id));if(!candidates.length)break;generated.push(candidates[Math.floor(Math.random()*candidates.length)])}}if(!generated.length){toast('Сначала выберите состав варианта');return}variant=generated;saveCurrent();go('builder');toast('Вариант сгенерирован')}
$('#clearVariant').onclick=()=>{variant=[];saveCurrent();toast('Вариант очищен')};
$('#saveVariantBtn').onclick=()=>{if(!variant.length){toast('Добавьте хотя бы одно задание');return}const saved=JSON.parse(localStorage.getItem('mathoge-saved')||'[]');saved.unshift({id:Date.now(),name:$('#variantName').value.trim()||'Тренировочный вариант',created:new Date().toLocaleDateString('ru-RU'),tasks:variant});localStorage.setItem('mathoge-saved',JSON.stringify(saved));toast('Вариант сохранён')};
function renderSaved(){const saved=JSON.parse(localStorage.getItem('mathoge-saved')||'[]');$('#savedEmpty').style.display=saved.length?'none':'block';$('#savedVariants').innerHTML=saved.map(v=>`<article class="saved-card"><h4>${v.name}</h4><p>${v.created} · ${v.tasks.length} заданий</p><div class="mini-variant">${v.tasks.slice(0,7).map(t=>`<span class="mini-chip">№${t.number}</span>`).join('')}</div><div class="saved-actions"><button class="secondary-button" data-load="${v.id}">Открыть</button><button class="ghost-button" data-delete="${v.id}">Удалить</button></div></article>`).join('');$$('[data-load]').forEach(b=>b.onclick=()=>{const v=saved.find(x=>x.id==b.dataset.load);variant=v.tasks;saveCurrent();go('builder')});$$('[data-delete]').forEach(b=>b.onclick=()=>{const next=saved.filter(x=>x.id!=b.dataset.delete);localStorage.setItem('mathoge-saved',JSON.stringify(next));renderSaved();toast('Вариант удалён')})}
$('#bankCount').textContent=tasks.length;initFilters();initGenerator();updateCounters();renderBuilder();
