// №13. Неравенства. Прототипы ФИПИ.
(function(){
  const existing=new Set(tasks.map(t=>t.id));
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const math=s=>`\\(${s}\\)`;
  const choices=values=>`<span class="number13-options">${values.map((value,index)=>`<span><b>${index+1})</b> ${value==='нет решений'?value:math(value)}${index<values.length-1?';':''}</span>`).join('')}</span>`;
  const fmt=n=>Number.isInteger(n)?String(n):String(Math.round(n*1000)/1000).replace('.',',');
  const info=spec=>{const p=Number(spec.prototype),s=String(spec.expression||'').replace(/\s+/g,'').replace(/\\le/g,'<=').replace(/\\ge/g,'>=');const strict=!s.includes('<=')&&!s.includes('>='),less=s.includes('<');let l=0,r=1,ll='0',rr='1';if(p===4){const m=s.match(/^(\d*)x-x\^2/),a=m?(m[1]?Number(m[1]):1):1;l=0;r=a;rr=fmt(a);return{l,r,ll,rr,strict,solution:less?'outside':'between'};}if(p===6){const m=s.match(/\(x([+-])(\d+(?:[.,]\d+)?)\)\(x([+-])(\d+(?:[.,]\d+)?)\)/);if(m){const a=(m[1]==='+'?-1:1)*Number(m[2].replace(',','.')),b=(m[3]==='+'?-1:1)*Number(m[4].replace(',','.'));l=Math.min(a,b);r=Math.max(a,b);ll=fmt(l);rr=fmt(r);}return{l,r,ll,rr,strict,solution:less?'between':'outside'};}if(p===8){const m=s.match(/^(\d*)x\^2(?:<=|>=|<|>)([\d.,]+)/),a=m&&m[1]?Number(m[1]):1,b=m?Number(m[2].replace(',','.')):1,x=Math.sqrt(b/a);l=-x;r=x;const sn=Math.sqrt(b),sd=Math.sqrt(a);if(Number.isInteger(sn)&&Number.isInteger(sd)){let n=sn,d=sd,g=(a,b)=>b?g(b,a%b):a,q=g(n,d);n/=q;d/=q;let z=d;while(z%2===0)z/=2;while(z%5===0)z/=5;rr=d===1?String(n):z===1?fmt(n/d):`${n}/${d}`;}else rr=fmt(x);ll=`−${rr}`;return{l,r,ll,rr,strict,solution:less?'between':'outside'};}return null;};
  const generatedDiagram=spec=>{const v=info(spec);if(!v)return null;const ans=Math.max(0,Math.min(3,(Number(spec.answer)||1)-1)),correct=v.solution,pool=['between','outside','left','right'].filter(x=>x!==correct),k=new Array(4);k[ans]=correct;let q=0;for(let i=0;i<4;i++)if(!k[i])k[i]=pool[q++];const id=`n13-${String(spec.id).replace(/[^a-zA-Z0-9_-]/g,'-')}`,closed=!v.strict;const dot=(x,y)=>closed?`<circle cx="${x}" cy="${y}" r="3" fill="#111"/>`:`<circle cx="${x}" cy="${y}" r="3" fill="#fff" stroke="#111" stroke-width="1.4"/>`;const one=(kind,i)=>{const ox=(i%2)*380,oy=Math.floor(i/2)*78,y=oy+30,a=145,b=235,h=190,start=42,end=330,shade=(x,w)=>`<rect x="${ox+x}" y="${y-8}" width="${w}" height="8" fill="url(#${id})"/>`;let sh='',mk='',lab='';if(kind==='between'){sh=shade(a,b-a);mk=dot(ox+a,y)+dot(ox+b,y);lab=`<text x="${ox+a}" y="${y+23}" text-anchor="middle">${esc(v.ll)}</text><text x="${ox+b}" y="${y+23}" text-anchor="middle">${esc(v.rr)}</text>`;}else if(kind==='outside'){sh=shade(start,a-start)+shade(b,end-b);mk=dot(ox+a,y)+dot(ox+b,y);lab=`<text x="${ox+a}" y="${y+23}" text-anchor="middle">${esc(v.ll)}</text><text x="${ox+b}" y="${y+23}" text-anchor="middle">${esc(v.rr)}</text>`;}else if(kind==='left'){sh=shade(start,h-start);mk=dot(ox+h,y);lab=`<text x="${ox+h}" y="${y+23}" text-anchor="middle">${esc(v.ll)}</text>`;}else{sh=shade(h,end-h);mk=dot(ox+h,y);lab=`<text x="${ox+h}" y="${y+23}" text-anchor="middle">${esc(v.rr)}</text>`;}return `<g><text x="${ox+7}" y="${y+5}" font-weight="600">${i+1})</text><line x1="${ox+start}" y1="${y}" x2="${ox+end}" y2="${y}" stroke="#111" stroke-width="1.5"/>${sh}${mk}${lab}<path d="M ${ox+end} ${y} l -10 -5 v 10 z" fill="#111"/><text x="${ox+end+9}" y="${y+5}" font-style="italic">x</text></g>`;};return `<svg class="number13-diagram number13-choice-diagram" viewBox="0 0 760 156" width="760" height="156" role="img" aria-label="Варианты ответа к заданию ${esc(spec.id)}"><defs><pattern id="${id}" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(25)"><line x1="0" y1="0" x2="0" y2="6" stroke="#111" stroke-width="1.2"/></pattern></defs><g font-family="Times New Roman,serif" font-size="16" fill="#111">${k.map(one).join('')}</g></svg>`;};
  const diagram=spec=>{if([4,6,8].includes(Number(spec.prototype))){const svg=generatedDiagram(spec);if(svg)return svg;}return `<img class="number13-diagram ${spec.prototype===10?'number13-condition-diagram':'number13-choice-diagram'}" src="${esc(spec.diagram)}" alt="${spec.prototype===10?'Решение неравенства':'Варианты ответа'} к заданию ${esc(spec.id)}" loading="lazy">`;};
  const textFor=spec=>{const p=Number(spec.prototype);if(p===10)return `Укажите неравенство, решение которого изображено на рисунке.${diagram(spec)}${choices(spec.choices)}`;const formula=p===2||p===3?math(`\\begin{cases}${spec.system[0]},\\\\${spec.system[1]}.\\end{cases}`):math(spec.expression);const prompt=p===2||p===3?'Укажите решение системы неравенств':'Укажите решение неравенства';return `${prompt} ${formula}.${spec.diagram?diagram(spec):choices(spec.choices)}`;};
  const subtopic=p=>p===1?'Линейные неравенства':p<=3?'Линейные системы неравенств':p<=9?'Квадратичные неравенства':'Неравенство по рисунку';
  const add=spec=>{if(existing.has(spec.id))return;tasks.push({id:spec.id,sourceId:spec.id,fipiId:spec.id,number:13,prototype:spec.prototype,kind:spec.kind,section:'Алгебра',topic:'Неравенства',subtopic:subtopic(Number(spec.prototype)),text:textFor(spec),answer:String(spec.answer),demo:!!spec.demo,latexMath:true,diagram:spec.diagram||null,sourcePage:spec.page,sourceCorrection:spec.sourceCorrection||null,answerCorrection:spec.answerCorrection||null});existing.add(spec.id);};
  window.MathOGENumber13={add};
  const specs=[{"id":"13.1","prototype":1,"kind":"Прототип","answer":"2","page":55,"expression":"-3-x<4x+7","choices":["(-\\infty;-0{,}8)","(-2;+\\infty)","(-\\infty;-2)","(-0{,}8;+\\infty)"]},{"id":"13.2","prototype":2,"kind":"Прототип","answer":"2","page":55,"system":["x+3 \\ge-2","x+1{,}1 \\ge 0"],"diagram":"assets/number13/diagram-13-2.png"},{"id":"13.3","prototype":3,"kind":"Прототип","answer":"1","page":55,"system":["x-2{,}6 \\le 0","x-1 \\ge 1"],"choices":["[2;2{,}6]","(-\\infty;2{,}6]","(-\\infty;2]\\cup [2{,}6;+\\infty)","[2;+\\infty)"]},{"id":"13.4","prototype":4,"kind":"Прототип","answer":"4","page":56,"expression":"x-x^2 \\ge 0","diagram":"assets/number13/diagram-13-4.png"},{"id":"13.5","prototype":5,"kind":"Прототип","answer":"4","page":56,"expression":"x-x^2<0","choices":["(0;1)","(0;+\\infty)","(1;+\\infty)","(-\\infty;0)\\cup (1;+\\infty)"]},{"id":"13.6","prototype":6,"kind":"Прототип","answer":"1","page":56,"expression":"(x+1)(x-6) \\le 0","diagram":"assets/number13/diagram-13-6.png"},{"id":"13.7","prototype":7,"kind":"Прототип","answer":"3","page":56,"expression":"(x+3)(x-6)>0","choices":["(6;+\\infty)","(-3;+\\infty)","(-\\infty;-3)\\cup (6;+\\infty)","(-3;6)"]},{"id":"13.8","prototype":8,"kind":"Прототип","answer":"1","page":57,"expression":"x^2<9","diagram":"assets/number13/diagram-13-8.png"},{"id":"13.9","prototype":9,"kind":"Прототип","answer":"1","page":57,"expression":"x^2-25>0","choices":["(-\\infty;-5)\\cup (5;+\\infty)","(-5;5)","нет решений","(-\\infty;+\\infty)"]},{"id":"13.10","prototype":10,"kind":"Прототип","answer":"3","page":57,"choices":["x^2-7x<0","x^2-49>0","x^2-7x>0","x^2-49<0"],"diagram":"assets/number13/diagram-13-10.png","demo":true}];
  specs.forEach(add);
})();
