// №12. Расчёты по формулам. Прототипы ФИПИ.
(function(){
  const existing=new Set(tasks.map(task=>task.id));
  const math=value=>`\\(${value}\\)`;
  const latexNumber=value=>String(value).replace('−','-').replace(',', '{,}');
  const number=value=>math(latexNumber(value));
  const textFor=spec=>{
    switch(Number(spec.prototype)){
      case 1:return `В фирме «Родник» стоимость (в рублях) колодца из железобетонных колец рассчитывается по формуле ${math('C=6000+4100n')}, где ${math('n')} — число колец, установленных в колодце. Пользуясь этой формулой, рассчитайте стоимость колодца из ${number(spec.rings)} колец. Ответ дайте в рублях.`;
      case 2:return `В фирме «Чистая вода» стоимость (в рублях) колодца из железобетонных колец рассчитывается по формуле ${math('C=6500+4000n')}, где ${math('n')} — число колец, установленных в колодце. Пользуясь этой формулой, рассчитайте стоимость колодца из ${number(spec.rings)} колец. Ответ дайте в рублях.`;
      case 3:return `Перевести значение температуры по шкале Фаренгейта в шкалу Цельсия позволяет формула ${math('t_{C}=\\frac{5}{9}(t_{F}-32)')}, где ${math('t_{C}')} — температура в градусах Цельсия, ${math('t_{F}')} — температура в градусах Фаренгейта. Скольким градусам по шкале Цельсия соответствует ${number(spec.temperature)} ${spec.degreesWord} по шкале Фаренгейта?`;
      case 4:return `Чтобы перевести значение температуры по шкале Цельсия в шкалу Фаренгейта, пользуются формулой ${math('t_{F}=1{,}8t_{C}+32')}, где ${math('t_{C}')} — температура в градусах Цельсия, ${math('t_{F}')} — температура в градусах Фаренгейта. Скольким градусам по шкале Фаренгейта соответствует ${number(spec.temperature)} ${spec.degreesWord} по шкале Цельсия?`;
      case 5:return `Сила Архимеда, выталкивающая на поверхность погружённое в воду тело, вычисляется по формуле ${math('F=\\rho gV')}, где ${math('\\rho=1000\\ \\text{кг/м}^{3}')} — плотность воды, ${math('g=9{,}8\\ \\text{м/с}^{2}')} — ускорение свободного падения, а ${math('V')} — объём тела в кубических метрах. Сила ${math('F')} измеряется в ньютонах. Найдите силу Архимеда, действующую на погружённое в воду тело объёмом ${number(spec.volume)} куб. м. Ответ дайте в ньютонах.`;
      case 6:return `Кинетическая энергия тела массой ${math('m')} кг, двигающегося со скоростью ${math('v')} м/с, вычисляется по формуле ${math('E=\\frac{mv^{2}}{2}')} и измеряется в джоулях (Дж). Известно, что автомобиль массой ${number(spec.mass)} кг обладает кинетической энергией ${number(spec.energyThousands)} тысяч джоулей. Найдите скорость этого автомобиля в метрах в секунду.`;
      case 7:return `Если тело массой ${math('m')} кг подвешено на высоте ${math('h')} м над горизонтальной поверхностью земли, то его потенциальная энергия в джоулях вычисляется по формуле ${math('P=mgh')}, где ${math('g=9{,}8\\ \\text{м/с}^{2}')} — ускорение свободного падения. Найдите массу тела, подвешенного на высоте ${number(spec.height)} м над поверхностью земли, если его потенциальная энергия равна ${number(spec.energy)} джоулям. Ответ дайте в килограммах.`;
      case 8:{const target=`d_{${spec.target}}`,known=`d_{${spec.known}}`;return `Площадь четырёхугольника можно вычислить по формуле ${math('S=\\frac{d_{1}d_{2}\\sin\\alpha}{2}')}, где ${math('d_{1}')} и ${math('d_{2}')} — длины диагоналей четырёхугольника, ${math('\\alpha')} — угол между диагоналями. Пользуясь этой формулой, найдите длину диагонали ${math(target)}, если ${math(`${known}=${spec.knownValue}`)}, ${math(`\\sin\\alpha=\\frac{${spec.sinNumerator}}{${spec.sinDenominator}}`)}, а ${math(`S=${latexNumber(spec.area)}`)}.`;}
      case 9:return `Мощность постоянного тока (в ваттах) вычисляется по формуле ${math('P=I^{2}R')}, где ${math('I')} — сила тока (в амперах), ${math('R')} — сопротивление (в омах). Пользуясь этой формулой, найдите сопротивление ${math('R')}, если мощность составляет ${number(spec.power)} Вт, а сила тока равна ${number(spec.current)} А. Ответ дайте в омах.`;
      case 10:return `Центростремительное ускорение при движении по окружности ${math('(\\text{в м/с}^{2})')} вычисляется по формуле ${math('a=\\omega^{2}R')}, где ${math('\\omega')} — угловая скорость ${math('(\\text{в с}^{-1})')}, ${math('R')} — радиус окружности (в метрах). Пользуясь этой формулой, найдите радиус ${math('R')}, если угловая скорость равна ${math(`${latexNumber(spec.omega)}\\ \\text{с}^{-1}`)}, а центростремительное ускорение равно ${math(`${latexNumber(spec.acceleration)}\\ \\text{м/с}^{2}`)}. Ответ дайте в метрах.`;
      case 11:{const capacitance=spec.capacitanceFactor===2?'2\\cdot10^{-4}':'10^{-4}';return `Энергия заряженного конденсатора ${math('W')} (в джоулях) вычисляется по формуле ${math('W=\\frac{CU^{2}}{2}')}, где ${math('C')} — ёмкость конденсатора (в фарадах), а ${math('U')} — разность потенциалов на обкладках конденсатора (в вольтах). Найдите энергию конденсатора ёмкостью ${math(capacitance)} фарад, если разность потенциалов на обкладках конденсатора равна ${number(spec.voltage)} вольт. Ответ дайте в джоулях.`;}
      default:return '';
    }
  };
  const add=spec=>{if(existing.has(spec.id))return;const prototype=Number(spec.prototype);tasks.push({id:spec.id,sourceId:spec.id,fipiId:spec.id,number:12,prototype,kind:spec.kind,section:'Алгебра',topic:'Расчёты по формулам',subtopic:prototype<=8?'Линейная зависимость':'Квадратичная зависимость',text:textFor(spec),answer:String(spec.answer),demo:spec.id==='12.6',latexMath:true});existing.add(spec.id);};
  window.MathOGENumber12={add};
  const specs=[{"id":"12.1","prototype":1,"kind":"Прототип","answer":"22400","rings":4},{"id":"12.2","prototype":2,"kind":"Прототип","answer":"50500","rings":11},{"id":"12.3","prototype":3,"kind":"Прототип","answer":"−80","temperature":"−112","degreesWord":"градусов"},{"id":"12.4","prototype":4,"kind":"Прототип","answer":"−148","temperature":"−100","degreesWord":"градусов"},{"id":"12.5","prototype":5,"kind":"Прототип","answer":"490","volume":"0,05"},{"id":"12.6","prototype":6,"kind":"Прототип","answer":"20","mass":1200,"energyThousands":240},{"id":"12.7","prototype":7,"kind":"Прототип","answer":"20","height":5,"energy":980},{"id":"12.8","prototype":8,"kind":"Прототип","answer":"4","target":1,"known":2,"knownValue":7,"sinNumerator":2,"sinDenominator":7,"area":"4"},{"id":"12.9","prototype":9,"kind":"Прототип","answer":"3","power":"6,75","current":"1,5"},{"id":"12.10","prototype":10,"kind":"Прототип","answer":"6","omega":"0,5","acceleration":"1,5"},{"id":"12.11","prototype":11,"kind":"Прототип","answer":"0,0072","capacitanceFactor":1,"voltage":12}];
  specs.forEach(add);
})();
