// Реальные задания из загруженного банка. Подключается после app.js и заменяет демо-карточки №6, №8, №10, №15.
const realTasks=[
{id:'6.1',number:6,prototype:1,section:'Алгебра',topic:'Дроби',subtopic:'Десятичные дроби',text:'Найдите значение выражения 5,6 + 9,7.',answer:'15,3'},
{id:'6.2',number:6,prototype:2,section:'Алгебра',topic:'Дроби',subtopic:'Десятичные дроби',text:'Найдите значение выражения 3,3 − 1,9.',answer:'1,4'},
{id:'6.3',number:6,prototype:3,section:'Алгебра',topic:'Дроби',subtopic:'Десятичные дроби',text:'Найдите значение выражения 1,6 · 5,1.',answer:'8,16'},
{id:'6.4',number:6,prototype:4,section:'Алгебра',topic:'Дроби',subtopic:'Десятичные дроби',text:'Найдите значение выражения 9,6 : 1,6.',answer:'6'},
{id:'6.5',number:6,prototype:5,section:'Алгебра',topic:'Дроби',subtopic:'Обыкновенные дроби',text:'Найдите значение выражения <span class="math">½ + 11⁄10</span>.',answer:'1,6'},
{id:'6.6',number:6,prototype:6,section:'Алгебра',topic:'Дроби',subtopic:'Обыкновенные дроби',text:'Найдите значение выражения <span class="math">½ − 9⁄10</span>.',answer:'−0,4'},
{id:'6.7',number:6,prototype:7,section:'Алгебра',topic:'Дроби',subtopic:'Обыкновенные дроби',text:'Найдите значение выражения <span class="math">15⁄2 · 7⁄5</span>.',answer:'10,5'},
{id:'6.8',number:6,prototype:8,section:'Алгебра',topic:'Дроби',subtopic:'Обыкновенные дроби',text:'Найдите значение выражения <span class="math">21⁄2 : 3⁄5</span>.',answer:'17,5'},
{id:'6.9',number:6,prototype:9,section:'Алгебра',topic:'Дроби',subtopic:'Обыкновенные дроби',text:'Представьте выражение <span class="math">3⁄5 − 2⁄7</span> в виде дроби со знаменателем 70. В ответ запишите числитель полученной дроби.',answer:'22'},
{id:'6.10',number:6,prototype:10,section:'Алгебра',topic:'Дроби',subtopic:'Обыкновенные дроби',text:'Найдите значение выражения <span class="math">1 1⁄30 + 1⁄42</span>.',answer:'37/35',demo:true},
{id:'8.9',number:8,prototype:9,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">√(4⁄4)</span>.',answer:'1'},
{id:'8.10',number:8,prototype:10,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">√(2 · 45) · √10</span>.',answer:'30'},
{id:'8.11',number:8,prototype:11,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">2√13 · 5√2 · √26</span>.',answer:'260'},
{id:'8.12',number:8,prototype:12,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">(√11 − 3)(√11 + 3)</span>.',answer:'2'},
{id:'8.13',number:8,prototype:13,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">(√5 − √2)(√5 + √2)</span>.',answer:'3'},
{id:'8.14',number:8,prototype:14,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">(√8 + √2) · √2</span>.',answer:'6'},
{id:'8.15',number:8,prototype:15,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">(√8 − √2) · √2</span>.',answer:'2'},
{id:'8.16',number:8,prototype:16,section:'Алгебра',topic:'Степени и корни',subtopic:'Вычисления с квадратными корнями',text:'Найдите значение выражения <span class="math">(√15 − 2)² + 4√15</span>.',answer:'19'},
{id:'10.1',number:10,prototype:1,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'В случайном опыте N = 30 равновозможных элементарных событий, из которых N(A) = 27 благоприятствуют событию A. Вычислите вероятность события A.',answer:'0,9',new:true},
{id:'10.2',number:10,prototype:2,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'У бабушки 10 чашек: 1 с красными цветами, остальные с синими. Бабушка наливает чай в случайно выбранную чашку. Найдите вероятность того, что это будет чашка с синими цветами.',answer:'0,9'},
{id:'10.3',number:10,prototype:3,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'В фирме такси в данный момент свободно 10 машин: 1 чёрная, 1 жёлтая и 8 зелёных. По вызову выехала одна из машин, случайно оказавшаяся ближе всего к заказчику. Найдите вероятность того, что к нему приедет жёлтое такси.',answer:'0,1'},
{id:'10.4',number:10,prototype:4,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'Родительский комитет закупил 10 пазлов для подарков детям в связи с окончанием учебного года, из них 3 с машинами и 7 с видами городов. Подарки распределяются случайным образом между 10 детьми, среди которых есть Миша. Найдите вероятность того, что Мише достанется пазл с машиной.',answer:'0,3'},
{id:'10.5',number:10,prototype:5,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'В лыжных гонках участвуют 7 спортсменов из России, 1 спортсмен из Швеции и 2 спортсмена из Норвегии. Порядок старта определяется жребием. Найдите вероятность того, что первым будет стартовать спортсмен из Швеции.',answer:'0,1'},
{id:'10.6',number:10,prototype:6,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'На экзамене 20 билетов, Андрей не выучил 1 из них. Найдите вероятность того, что ему попадётся выученный билет.',answer:'0,95'},
{id:'10.7',number:10,prototype:7,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'Под классной доской в лотке лежат 18 чёрных и 22 синих маркера для доски. Из коробки берут случайный маркер. Найдите вероятность того, что он окажется синим.',answer:'0,55',new:true},
{id:'10.8',number:10,prototype:8,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'В магазине канцтоваров продаётся 84 ручки: 22 красных, 9 зелёных, 41 фиолетовая, остальные синие и чёрные, их поровну. Найдите вероятность того, что случайно выбранная ручка окажется красной или фиолетовой.',answer:'0,75'},
{id:'10.9',number:10,prototype:9,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'Из ящика, где хранятся 7 жёлтых и 14 зелёных карандашей, не глядя достали два карандаша. Известно, что первый карандаш оказался зелёным. Найдите вероятность того, что второй карандаш тоже окажется зелёным.',answer:'0,65',new:true},
{id:'10.10',number:10,prototype:10,section:'Алгебра',topic:'Вероятности',subtopic:'Классическое определение вероятности',text:'Симметричный игральный кубик бросают два раза. Найдите вероятность события «сумма выпавших очков равна 3, 4 или 5».',answer:'1/4',demo:true,new:true},
{id:'10.12',number:10,prototype:12,section:'Алгебра',topic:'Вероятности',subtopic:'Статистическое определение вероятности',text:'В среднем из 50 карманных фонариков, поступивших в продажу, пять неисправных. Найдите вероятность того, что выбранный наудачу в магазине фонарик окажется исправен.',answer:'0,9'},
{id:'10.13',number:10,prototype:13,section:'Алгебра',topic:'Вероятности',subtopic:'Вероятность противоположного события',text:'Вероятность того, что новая шариковая ручка пишет плохо (или не пишет), равна 0,02. Покупатель выбирает одну ручку. Найдите вероятность того, что эта ручка пишет хорошо.',answer:'0,98'},
{id:'15.1',number:15,prototype:1,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Углы треугольника',text:'В треугольнике два угла равны 28° и 93°. Найдите его третий угол. Ответ дайте в градусах.',answer:'59'},
{id:'15.3',number:15,prototype:3,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Углы треугольника',text:'Один из острых углов прямоугольного треугольника равен 18°. Найдите его другой острый угол. Ответ дайте в градусах.',answer:'72'},
{id:'15.4',number:15,prototype:4,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Углы треугольника',text:'В треугольнике ABC известно, что AB = BC, ∠ABC = 102°. Найдите угол BCA. Ответ дайте в градусах.',answer:'39'},
{id:'15.5',number:15,prototype:5,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Углы треугольника',text:'В равнобедренном треугольнике ABC с основанием AC внешний угол при вершине C равен 123°. Найдите величину угла ABC. Ответ дайте в градусах.',answer:'66'},
{id:'15.6',number:15,prototype:6,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Медиана, биссектриса, высота и средняя линия',text:'В треугольнике ABC известно, что ∠BAC = 24°, AD — биссектриса. Найдите угол BAD. Ответ дайте в градусах.',answer:'12'},
{id:'15.10',number:15,prototype:10,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Медиана, биссектриса, высота и средняя линия',text:'В треугольнике ABC известно, что AC = 12, BM — медиана, BM = 11. Найдите AM.',answer:'6'},
{id:'15.11',number:15,prototype:11,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Медиана, биссектриса, высота и средняя линия',text:'Медиана равностороннего треугольника равна <span class="math">9√3</span>. Найдите сторону этого треугольника.',answer:'18'},
{id:'15.12',number:15,prototype:12,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Медиана, биссектриса, высота и средняя линия',text:'Биссектриса равностороннего треугольника равна <span class="math">11√3</span>. Найдите сторону этого треугольника.',answer:'22'},
{id:'15.13',number:15,prototype:13,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Медиана, биссектриса, высота и средняя линия',text:'Высота равностороннего треугольника равна <span class="math">11√3</span>. Найдите сторону этого треугольника.',answer:'22'},
{id:'15.14',number:15,prototype:14,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Медиана, биссектриса, высота и средняя линия',text:'Сторона равностороннего треугольника равна <span class="math">10√3</span>. Найдите биссектрису этого треугольника.',answer:'15'},
{id:'15.15',number:15,prototype:15,section:'Геометрия',topic:'Треугольники и их элементы',subtopic:'Медиана, биссектриса, высота и средняя линия',text:'Сторона равностороннего треугольника равна <span class="math">10√3</span>. Найдите медиану этого треугольника.',answer:'15'}
].map(t=>({demo:false,new:false,...t,real:true}));

// Заменяем только четыре выбранных номера, остальные разделы прототипа оставляем без изменений.
for(let i=tasks.length-1;i>=0;i--) if([6,8,10,15].includes(tasks[i].number)) tasks.splice(i,1);
tasks.push(...realTasks);tasks.sort((a,b)=>a.number-b.number||a.prototype-b.prototype);

// Карточки с реальным условием, под-темой и раскрываемым ответом.
card=function(t){let a=variant.some(v=>v.id===t.id);return `<article class="task-card"><div><div class="task-meta"><span class="tag number">№${t.number}</span><span class="tag">${t.section}</span><span class="tag">${t.topic}</span>${t.subtopic?`<span class="tag">${t.subtopic}</span>`:''}<span class="tag">Прототип ${t.prototype}</span>${t.demo?'<span class="tag demo">DEMO</span>':''}${t.new?'<span class="tag new">NEW</span>':''}</div><h4>${t.text}</h4>${t.real?`<div class="real-card-actions"><button class="answer-toggle" data-answer="${t.id}">Показать ответ</button><span class="card-answer" id="answer-${t.id}">Ответ: <b>${t.answer}</b></span></div>`:''}</div><div class="task-side"><span class="task-id">ID ${t.id}</span><button class="add-button ${a?'added':''}" data-add="${t.id}">${a?'✓ Добавлено':'+ В вариант'}</button></div></article>`};
const oldRenderTasks=renderTasks;renderTasks=function(){oldRenderTasks();document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{let e=document.getElementById('answer-'+b.dataset.answer);e.classList.toggle('visible');b.textContent=e.classList.contains('visible')?'Скрыть ответ':'Показать ответ'})};
renderBuilderBank=function(){let q=builderSearch.value.toLowerCase(),n=builderNumberFilter.value,s=builderSectionFilter.value,l=tasks.filter(t=>(!q||`${t.id} ${t.topic} ${t.subtopic||''} ${t.text}`.toLowerCase().includes(q))&&(!n||t.number==n)&&(!s||t.section===s));builderBankCount.textContent=l.length;builderBankList.innerHTML=l.map(t=>{let a=variant.some(v=>v.id===t.id);return `<article class="builder-bank-card"><div><div class="task-meta"><span class="tag number">№${t.number}</span><span class="tag">${t.topic}</span><span class="tag">P${t.prototype}</span></div><h4>${t.text}</h4><p>${t.subtopic||t.section} · ID ${t.id}</p></div><button class="add-button ${a?'added':''}" data-builder-add="${t.id}">${a?'✓':'+'}</button></article>`}).join('');document.querySelectorAll('[data-builder-add]').forEach(b=>b.onclick=()=>addTask(b.dataset.builderAdd))};
renderPreview=function(){let name=variantName.value.trim()||'Тренировочный вариант';previewTitle.textContent=name;previewMeta.textContent=`${variant.length} заданий · часть 1: ${variant.filter(t=>t.number<=19).length} · часть 2: ${variant.filter(t=>t.number>=20).length}`;previewList.innerHTML=variant.length?variant.map((t,i)=>`<article class="preview-task"><div class="preview-task-number">${i+1}.</div><div><h4>Задание №${t.number}</h4><p>${t.text}</p>${t.number<=19?'<div class="answer-line"><span>Ответ:</span><div class="answer-boxes"></div></div>':'<div class="solution-space"></div>'}<div class="answer-key">Ответ: ${t.answer||'—'}</div></div></article>`).join(''):'<p class="muted">Вариант пуст.</p>'};
bankCount.textContent=tasks.length;renderTasks();renderBuilderBank();
